---
- hosts: localhost
  tasks:
  - name: Stop service httpd, if started
    service:
      name: httpd
      state: stopped

  - name: Enable to install NGINX.
    shell: "amazon-linux-extras enable nginx1"
    become: yes

  - name: Install NGINX.
    yum: name=nginx


  - name: Start Nginx
  service:
    name: nginx
    state: restart
